
CREATE TABLE TB_CLIENTS(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255),
    ADDRESS VARCHAR(255) NOT NULL,
    ANUALINCOME DOUBLE PRECISION,
);

CREATE TABLE TB_CONSULTANTS(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255),
    ADDRESS VARCHAR(255) NOT NULL,
    SALARY DOUBLE PRECISION,
);

CREATE TABLE TB_PROPERTIES(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    PRICE DOUBLE PRECISION NOT NULL,
);

CREATE TABLE TB_ORDERS_PROPERTIES(
    ID BIGSERIAL PRIMARY KEY NOT NULL,

    ID_ORDER BIGSERIAL,,
    ID_PROPERTY BIGSERIAL,

    FOREIGN KEY(ID_ORDER) REFERENCES TB_ORDERS(ID),
    FOREIGN KEY(ID_PROPERTY) REFERENCES TB_PROPERTIES(ID)
);

CREATE TABLE TB_ORDERS(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    OBSERVATIONS VARCHAR(255),

    ID_CONSULTANT BIGINT,
    ID_CLIENT BIGINT,
    ID_ORDERS_PROPERTIES BIGINT,

    FOREIGN KEY(ID_CONSULTANT) REFERENCES TB_CONSULTANTS(ID),
    FOREIGN KEY(ID_CLIENT) REFERENCES TB_CLIENTS(ID),
    FOREIGN KEY(ID_ORDERS_PROPERTIES) REFERENCES TB_ORDERS_PROPERTIES(ID)
);